steps:

  - label: ":nsp:"
    command: yarn run nsp
    agents:
      # Because this is an hourly scheduled build, we don't want to use the
      # elastic agents because then the stack will never scale in. The
      # docker builders are our next best thing.
      queue: elastic-builders
    plugins:
      docker-compose#v2.3.0:
        # We check for node dep vulnerabilities in our prod image, because
        # that's whats running the site
        config: docker-compose.prod.yml
        run: site

  - label: ":retirejs:"
    command: yarn run retire
    agents:
      # Because this is an hourly scheduled build, we don't want to use the
      # elastic agents because then the stack will never scale in. The
      # docker builders are our next best thing.
      queue: elastic-builders
    plugins:
      docker-compose#v2.3.0:
        # We check for frontend JS dep vulnerabilities in our dev image, because
        # that's before packaging etc
        config: docker-compose.yml
        run: site
